name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  eliasjpr/http2-testing:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run HTTP2 Server
      run: crystal ./examples/server.cr .&
    - name: Run H2 Spec
      run: h2spec -p 9876 -k -t -S
