name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  eliasjpr/http2-testing:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run HTTP2 Server
      run: crystal ./examples/server.cr .&
    - name: Run H2 Load
      run: h2load -n 100000 -c 100 -t 1 -T 2 -m 32 https://127.0.0.1:9876
